import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_crashlytics/firebase_crashlytics.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

import 'firebase_options.dart';
import 'screens/welcome_screen.dart';
import 'screens/main_navigation_shell.dart';
import 'screens/intro_carousel_screen.dart';
import 'services/app_events.dart';
import 'services/database_helper.dart';
import 'services/notification_service.dart';
import 'screens/widgets/app_loading.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Firebase config is generated by `flutterfire configure` into firebase_options.dart.
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // 1. Initialize Stability Monitoring (Crashlytics)
  FlutterError.onError = (errorDetails) {
    FirebaseCrashlytics.instance.recordFlutterFatalError(errorDetails);
  };
  PlatformDispatcher.instance.onError = (error, stack) {
    FirebaseCrashlytics.instance.recordError(error, stack, fatal: true);
    return true;
  };

  // 2. Initialize Local Notifications
  try {
    await NotificationService.instance.init();
    
    // 3. Schedule Production Reminders
    await NotificationService.instance.scheduleDailyReminder(
      id: 101,
      title: 'Time for Lunch? 🥗',
      body: 'A quick log now keeps your streak alive!',
      hour: 12,
      minute: 0,
    );
    
    await NotificationService.instance.scheduleDailyReminder(
      id: 102,
      title: 'Dinner Log 🍱',
      body: 'Don\'t forget to track your dinner to see your daily balance.',
      hour: 19,
      minute: 0,
    );
  } catch (e) {
    debugPrint('Notification scheduling failed: $e');
  }

  runApp(const FoodGApp());
}

class FoodGApp extends StatefulWidget {
  const FoodGApp({super.key});

  @override
  State<FoodGApp> createState() => _FoodGAppState();
}

class _FoodGAppState extends State<FoodGApp> {
  ThemeMode _themeMode = ThemeMode.system;

  @override
  void initState() {
    super.initState();
    _loadTheme();
    AppEvents.instance.profileChanged.addListener(_loadTheme);
  }

  @override
  void dispose() {
    AppEvents.instance.profileChanged.removeListener(_loadTheme);
    super.dispose();
  }

  Future<void> _loadTheme() async {
    final user = FirebaseAuth.instance.currentUser;
    if (user != null) {
      final profile = await DatabaseHelper.instance.getUserProfile(user.uid);
      if (profile != null) {
        setState(() {
          if (profile.themeMode == 'Light') {
            _themeMode = ThemeMode.light;
          } else if (profile.themeMode == 'Dark') {
            _themeMode = ThemeMode.dark;
          } else {
            _themeMode = ThemeMode.system;
          }
        });
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'FoodGApp',
      debugShowCheckedModeBanner: false,
      themeMode: _themeMode,
      scrollBehavior: const _NoStretchScrollBehavior(),
      theme: ThemeData(
        brightness: Brightness.light,
        useMaterial3: true,
        colorScheme: ColorScheme.fromSeed(
          seedColor: Colors.green,
          brightness: Brightness.light,
          surface: const Color(0xFFFFFFFF),
          surfaceContainer: const Color(0xFFFFFFFF),
        ),
        scaffoldBackgroundColor: const Color(0xFFF2EFE4),
        cardColor: const Color(0xFFFFFFFF),
        cardTheme: CardThemeData(
          color: const Color(0xFFFFFFFF),
          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(24)),
          elevation: 0,
        ),
        textTheme: const TextTheme(
          displayLarge: TextStyle(color: Colors.black, fontWeight: FontWeight.bold),
          headlineMedium: TextStyle(color: Colors.black, fontWeight: FontWeight.bold),
          titleLarge: TextStyle(color: Colors.black, fontWeight: FontWeight.bold),
          bodyLarge: TextStyle(color: Colors.black),
          bodyMedium: TextStyle(color: Colors.black87),
        ),
        snackBarTheme: const SnackBarThemeData(
          backgroundColor: Colors.transparent,
          elevation: 0,
          behavior: SnackBarBehavior.floating,
        ),
      ),
      darkTheme: ThemeData(
        brightness: Brightness.dark,
        colorScheme: ColorScheme.fromSeed(
          seedColor: Colors.green,
          brightness: Brightness.dark,
          surface: const Color(0xFF121212),
        ),
        scaffoldBackgroundColor: const Color(0xFF121212),
        cardColor: const Color(0xFF1E1E1E),
        useMaterial3: true,
        snackBarTheme: const SnackBarThemeData(
          backgroundColor: Colors.transparent,
          elevation: 0,
          behavior: SnackBarBehavior.floating,
        ),
        cardTheme: CardThemeData(
          color: const Color(0xFF1E1E1E),
          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(24)),
          elevation: 0,
        ),
      ),
      home: const AuthGate(),
    );
  }
}

class _NoStretchScrollBehavior extends MaterialScrollBehavior {
  const _NoStretchScrollBehavior();

  @override
  Widget buildOverscrollIndicator(
    BuildContext context,
    Widget child,
    ScrollableDetails details,
  ) =>
      child;
}

class AuthGate extends StatefulWidget {
  const AuthGate({super.key});

  @override
  State<AuthGate> createState() => _AuthGateState();
}

class _AuthGateState extends State<AuthGate> {
  bool? _introSeen;

  @override
  void initState() {
    super.initState();
    _loadIntroStatus();
  }

  Future<void> _loadIntroStatus() async {
    final prefs = await SharedPreferences.getInstance();
    if (mounted) {
      setState(() {
        _introSeen = prefs.getBool('intro_seen') ?? false;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    // 1. Wait for Intro Status to load initially
    if (_introSeen == null) {
      return const Scaffold(body: AppLoading());
    }

    return StreamBuilder<User?>(
      stream: FirebaseAuth.instance.authStateChanges(),
      builder: (context, snapshot) {
        // 2. Loading Auth State
        if (snapshot.connectionState == ConnectionState.waiting) {
          return const Scaffold(body: AppLoading());
        }

        final user = snapshot.data;

        // 3. Authenticated: Show the App Shell
        if (user != null) {
          return const MainNavigationShell();
        }

        // 4. Unauthenticated: Intro vs Welcome
        if (_introSeen == true) {
          return const WelcomeScreen();
        }
        
        return const IntroCarouselScreen();
      },
    );
  }
}
