import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';

import 'firebase_options.dart';
import 'screens/welcome_screen.dart';
import 'screens/main_navigation_shell.dart';
import 'services/app_events.dart';
import 'services/database_helper.dart';
import 'screens/widgets/app_loading.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Firebase config is generated by `flutterfire configure` into firebase_options.dart.
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const FoodGApp());
}

class FoodGApp extends StatefulWidget {
  const FoodGApp({super.key});

  @override
  State<FoodGApp> createState() => _FoodGAppState();
}

class _FoodGAppState extends State<FoodGApp> {
  ThemeMode _themeMode = ThemeMode.system;

  @override
  void initState() {
    super.initState();
    _loadTheme();
    AppEvents.instance.profileChanged.addListener(_loadTheme);
  }

  @override
  void dispose() {
    AppEvents.instance.profileChanged.removeListener(_loadTheme);
    super.dispose();
  }

  Future<void> _loadTheme() async {
    final user = FirebaseAuth.instance.currentUser;
    if (user != null) {
      final profile = await DatabaseHelper.instance.getUserProfile(user.uid);
      if (profile != null) {
        setState(() {
          if (profile.themeMode == 'Light') {
            _themeMode = ThemeMode.light;
          } else if (profile.themeMode == 'Dark') {
            _themeMode = ThemeMode.dark;
          } else {
            _themeMode = ThemeMode.system;
          }
        });
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'FoodGApp',
      debugShowCheckedModeBanner: false,
      themeMode: _themeMode,
      // Disable Android's default "stretch" overscroll so scrolling stops
      // cleanly at the edges instead of stretching the content.
      scrollBehavior: const _NoStretchScrollBehavior(),
      theme: ThemeData(
        brightness: Brightness.light,
        useMaterial3: true,
        colorScheme: ColorScheme.fromSeed(
          seedColor: Colors.green,
          brightness: Brightness.light,
          surface: const Color(0xFFFFFFFF),
          surfaceContainer: const Color(0xFFFFFFFF),
        ),
        scaffoldBackgroundColor: const Color(0xFFF2EFE4),
        cardColor: const Color(0xFFFFFFFF),
        cardTheme: CardThemeData(
          color: const Color(0xFFFFFFFF),
          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(24)),
          elevation: 0,
        ),
        textTheme: const TextTheme(
          displayLarge: TextStyle(color: Colors.black, fontWeight: FontWeight.bold),
          headlineMedium: TextStyle(color: Colors.black, fontWeight: FontWeight.bold),
          titleLarge: TextStyle(color: Colors.black, fontWeight: FontWeight.bold),
          bodyLarge: TextStyle(color: Colors.black),
          bodyMedium: TextStyle(color: Colors.black87),
        ),
        snackBarTheme: const SnackBarThemeData(
          backgroundColor: Colors.transparent,
          elevation: 0,
          behavior: SnackBarBehavior.floating,
        ),
      ),
      darkTheme: ThemeData(
        brightness: Brightness.dark,
        colorScheme: ColorScheme.fromSeed(
          seedColor: Colors.green,
          brightness: Brightness.dark,
          surface: const Color(0xFF121212),
        ),
        scaffoldBackgroundColor: const Color(0xFF121212),
        cardColor: const Color(0xFF1E1E1E),
        useMaterial3: true,
        snackBarTheme: const SnackBarThemeData(
          backgroundColor: Colors.transparent,
          elevation: 0,
          behavior: SnackBarBehavior.floating,
        ),
        cardTheme: CardThemeData(
          color: const Color(0xFF1E1E1E),
          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(24)),
          elevation: 0,
        ),
      ),
      home: const AuthGate(),
    );
  }
}

/// Scroll behavior that removes the stretch/glow overscroll indicator so lists
/// stop cleanly at their edges. Applied app-wide via [MaterialApp.scrollBehavior].
class _NoStretchScrollBehavior extends MaterialScrollBehavior {
  const _NoStretchScrollBehavior();

  @override
  Widget buildOverscrollIndicator(
    BuildContext context,
    Widget child,
    ScrollableDetails details,
  ) =>
      child;
}

/// Shows [HomeScreen] when a user is signed in, otherwise [LoginScreen].
///
/// Listens to Firebase auth state so signing in/out swaps screens automatically.
class AuthGate extends StatelessWidget {
  const AuthGate({super.key});

  @override
  Widget build(BuildContext context) {
    return StreamBuilder<User?>(
      stream: FirebaseAuth.instance.authStateChanges(),
      builder: (context, snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return const Scaffold(
            body: Center(child: AppLoading()),
          );
        }
        if (snapshot.hasData) {
          // Use const to help Flutter optimize rebuilds
          return const MainNavigationShell();
        }
        return const WelcomeScreen();
      },
    );
  }
}
