import 'package:flutter/material.dart';

enum LegalContentType { terms, privacy }

class LegalContentScreen extends StatelessWidget {
  final LegalContentType contentType;

  const LegalContentScreen({super.key, required this.contentType});

  @override
  Widget build(BuildContext context) {
    final isDark = Theme.of(context).brightness == Brightness.dark;
    final title = contentType == LegalContentType.terms ? 'Terms of Use' : 'Privacy Policy';

    return Scaffold(
      backgroundColor: isDark ? const Color(0xFF121212) : const Color(0xFFF2EFE4),
      appBar: AppBar(
        backgroundColor: Colors.transparent,
        elevation: 0,
        leading: IconButton(
          icon: Icon(Icons.arrow_back, color: isDark ? Colors.white : Colors.black),
          onPressed: () => Navigator.pop(context),
        ),
        title: Text(
          title,
          style: TextStyle(color: isDark ? Colors.white : Colors.black, fontWeight: FontWeight.bold),
        ),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(24.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              'Last Updated: July 2026',
              style: TextStyle(color: isDark ? Colors.white38 : Colors.black38, fontSize: 14),
            ),
            const SizedBox(height: 24),
            if (contentType == LegalContentType.terms)
              _buildTermsOfUse(isDark)
            else
              _buildPrivacyPolicy(isDark),
            const SizedBox(height: 48),
          ],
        ),
      ),
    );
  }

  Widget _buildTermsOfUse(bool isDark) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        _section('1. Acceptance of Terms', 
          'By accessing and using FoodGapp, you agree to be bound by these Terms of Use. If you do not agree, please do not use the application.'),
        _section('2. Health Disclaimer', 
          'FoodGapp is a nutritional tracking and planning tool. It is NOT a medical device. The information provided, including AI-generated meal plans, is for educational purposes only. Always consult with a healthcare professional before starting a new diet or fitness program.'),
        _section('3. FoodGapp AI Accuracy', 
          'Meal plans and nutritional estimates are generated by the FoodGapp AI Engine. While we strive for accuracy based on DOST-FNRI and USDA standards, AI outputs may contain errors. Users are responsible for verifying specific nutritional needs.'),
        _section('4. User Responsibility', 
          'You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account.'),
        _section('5. Data Usage', 
          'We utilize local-first storage and Firebase Authentication to provide our services. Your use of the app constitutes consent to our data processing practices as outlined in the Privacy Policy.'),
      ],
    );
  }

  Widget _buildPrivacyPolicy(bool isDark) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        _section('1. Data Collection', 
          'FoodGapp collects biometric data (age, weight, height, gender) to calculate personalized nutritional targets based on DOST-FNRI guidelines.'),
        _section('2. Local-First Storage', 
          'Most of your personal data, including meal logs, weight history, and saved recipes, is stored locally on your device in a secure SQLite database. This data is not uploaded to our servers.'),
        _section('3. Authentication Security', 
          'We use Google Firebase Authentication for secure identity management. Your password is encrypted and never stored in plain text by our system.'),
        _section('4. Third-Party Services', 
          'We utilize Gemini AI (Google) and Spoonacular APIs to provide intelligent nutritional analysis and recipe discovery. Data sent to these services is anonymized where possible.'),
        _section('5. Your Rights', 
          'As a local-first application, you have full control over your data. You can clear your logs at any time through the Profile settings or by uninstalling the application.'),
      ],
    );
  }

  Widget _section(String title, String content) {
    return Builder(
      builder: (context) {
        final isDark = Theme.of(context).brightness == Brightness.dark;
        return Padding(
          padding: const EdgeInsets.only(bottom: 24.0),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(
                title,
                style: TextStyle(
                  fontSize: 18,
                  fontWeight: FontWeight.bold,
                  color: isDark ? Colors.white : Colors.black,
                ),
              ),
              const SizedBox(height: 8),
              Text(
                content,
                style: TextStyle(
                  fontSize: 15,
                  height: 1.6,
                  color: isDark ? Colors.white70 : Colors.black87,
                ),
              ),
            ],
          ),
        );
      }
    );
  }
}
